/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Material_Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Proveedores_Formulario
     */
    public Material_Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblInstrumento = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtfCantidad = new javax.swing.JTextField();
        txtfValor = new javax.swing.JTextField();
        txtfFecha = new javax.swing.JTextField();
        btnAdquisicion = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtfMarca = new javax.swing.JTextField();
        txtfInstrumento = new javax.swing.JTextField();
        txtfCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtfNombre = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtfId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Material Nuevo");

        pnlFondo.setBackground(new java.awt.Color(0, 0, 0));

        lblTitulo.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Formulario De Material Nuevo");

        lblCorreo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("correo Proveedor:");

        lblInstrumento.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblInstrumento.setForeground(new java.awt.Color(255, 255, 255));
        lblInstrumento.setText("Instrumento o accesorio:");

        lblMarca.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Marca y modelo:");

        lblValor.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 255, 255));
        lblValor.setText("Valor total:");

        lblCantidad.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad:");

        lblFecha.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha:");

        txtfCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCantidadActionPerformed(evt);
            }
        });

        txtfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfValorActionPerformed(evt);
            }
        });

        btnAdquisicion.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnAdquisicion.setText("ADQUIRIR PRODUCTO");
        btnAdquisicion.setBorder(new javax.swing.border.MatteBorder(null));

        btnRegresar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("nombre proveedor:");

        lblId.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("ID:");

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorreo)
                            .addComponent(lblMarca)
                            .addComponent(lblCantidad)
                            .addComponent(lblValor)
                            .addComponent(lblFecha)
                            .addComponent(lblInstrumento)
                            .addComponent(jLabel1)
                            .addComponent(lblId))
                        .addGap(38, 38, 38)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(txtfValor)
                            .addComponent(txtfMarca)
                            .addComponent(txtfInstrumento)
                            .addComponent(txtfCorreo)
                            .addComponent(txtfNombre)
                            .addComponent(txtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblTitulo)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnAdquisicion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTitulo)
                .addGap(79, 79, 79)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstrumento)
                    .addComponent(txtfInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdquisicion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCantidadActionPerformed

    private void txtfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfValorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdquisicion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInstrumento;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextField txtfCantidad;
    private javax.swing.JTextField txtfCorreo;
    private javax.swing.JTextField txtfFecha;
    private javax.swing.JTextField txtfId;
    private javax.swing.JTextField txtfInstrumento;
    private javax.swing.JTextField txtfMarca;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfValor;
    // End of variables declaration//GEN-END:variables
    public void añadirMat(ActionListener listener) {
        btnAdquisicion.addActionListener(listener);
    }
    public void cambiarTablaProveedor(ActionListener listener) {
        btnRegresar.addActionListener(listener);
    }

    public String getTxtfCorreo() {
        return txtfCorreo.getText();
    }

    public String getTxtfFecha() {
        return txtfFecha.getText();
    }

    public int getTxtfId() {
        return Integer.parseInt(txtfId.getText());
    }

    public String getTxtfInstrumento() {
        return txtfInstrumento.getText();
    }

    public String getTxtfMarca() {
        return txtfMarca.getText();
    }

    public String getTxtfNombre() {
        return txtfNombre.getText();
    }

    public double getTxtfValor() {
        return Double.parseDouble(txtfValor.getText());
    }

    public int getTxtfCantidad() {
        return Integer.parseInt(txtfCantidad.getText());
    }
    public boolean validar(){
        boolean s = true;
        String ms ="Falta:\n";
        
        if(txtfId.getText().length()<=0){
            s=false;
            ms=ms+" La ID\n";
        }
        if(txtfNombre.getText().length()<=0){
            s=false;
            ms=ms+" El nombre\n";
        }
        
        if(txtfCorreo.getText().length()<=0){
            s=false;
            ms=ms+" El correo\n";
        }
        
        if(txtfInstrumento.getText().length()<=0){
            s=false;
            ms=ms+" El instrumento o accesorio\n";
        }
        if(txtfMarca.getText().length()<=0){
            s=false;
            ms=ms+" La marca y modelo\n";
        }
        if(txtfCantidad.getText().length()<=0){
            s=false;
            ms=ms+" La cantidad\n";
        }
        if(txtfValor.getText().length()<=0){
            s=false;
            ms=ms+" El valor total\n";
        }
        if(txtfFecha.getText().length()<=0){
            s=false;
            ms=ms+" La fecha\n";
        }

        if(!s){
        JOptionPane.showMessageDialog(this, ms, "Campos sin registrar", JOptionPane.ERROR_MESSAGE);
        }
        return s;
     }
     public void limpiar(){        
        txtfId.setText("");
        txtfNombre.setText("");
        txtfCorreo.setText("");
        txtfInstrumento.setText("");
        txtfMarca.setText("");
        txtfCantidad.setText("");
        txtfValor.setText("");
        txtfFecha.setText("");

    }
    
}
